// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDInFr409-PJV3iLTbJEDqPhpuxzq_-q4w',
    appId: '1:673684476864:web:6815b884cd0b1eb2516e25',
    messagingSenderId: '673684476864',
    projectId: 'becation-eac04',
    authDomain: 'becation-eac04.firebaseapp.com',
    storageBucket: 'becation-eac04.firebasestorage.app',
    measurementId: 'G-00G4KPLNSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi83kf-7I_geDwKd_5LtwUqhjy10FRSW4',
    appId: '1:673684476864:android:ac1b3975eb9a5d38516e25',
    messagingSenderId: '673684476864',
    projectId: 'becation-eac04',
    storageBucket: 'becation-eac04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9XfZj1XrxQ6-vl_HE2nVUUHAARD_Es2U',
    appId: '1:673684476864:ios:095fbb3cb99a71a2516e25',
    messagingSenderId: '673684476864',
    projectId: 'becation-eac04',
    storageBucket: 'becation-eac04.firebasestorage.app',
    iosClientId: '673684476864-avk00sa4cmg9uote1ee7eu38cvgq8cb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.becationApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9XfZj1XrxQ6-vl_HE2nVUUHAARD_Es2U',
    appId: '1:673684476864:ios:095fbb3cb99a71a2516e25',
    messagingSenderId: '673684476864',
    projectId: 'becation-eac04',
    storageBucket: 'becation-eac04.firebasestorage.app',
    iosClientId: '673684476864-avk00sa4cmg9uote1ee7eu38cvgq8cb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.becationApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDInFr409-PJV3iLTbJEDqPhpuxzq_-q4w',
    appId: '1:673684476864:web:50b0f10c774ec232516e25',
    messagingSenderId: '673684476864',
    projectId: 'becation-eac04',
    authDomain: 'becation-eac04.firebaseapp.com',
    storageBucket: 'becation-eac04.firebasestorage.app',
    measurementId: 'G-7B2P6LW30K',
  );
}
